# Requests for some quick testing of the REST API
#
# Please remove authentiction check before running these requests because they
# do not have JWT tokens. For proper testing with authentication on, please run
# the Jasmine specs using "npm test".

### Get All books

GET http://localhost:3000/api/books/ HTTP/1.1

### Delete Book

DELETE http://localhost:3000/api/books/222222222222222222222222 HTTP/1.1
